Feature/svc 2986: convert to ZPL
zenoss/ZenPacks.zenoss.CheckPointMonitor pull request #7
Opened 2021-07-06 12:53 UTC by mkotovska

2021-07-06 13:18 UTC, StevePC requested changes

2021-07-06 13:18 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/zenpack.yaml
> +                rpn: ${here/totalBlocks},/,100,*
need to test this.  May need to convert to Configurable Datapoint

2021-07-06 13:18 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/zenpack.yaml
> +            commandTemplate: check_checkPointDtpsState.py -H ${here/manageIp} -c '${here/zSnmpCommunity}' -v ${here/zSnmpVer} -p ${here/zSnmpPort} -t ${here/zSnmpTimeout} -u '${here/zSnmpSecurityName
may need to put the path to the ZP dir

2021-07-06 13:18 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/zenpack.yaml
> +    remove: true
probably should not remove

2021-07-06 13:18 UTC, StevePC commented on setup.py
> +INSTALL_REQUIRES = ['ZenPacks.zenoss.ZenPackLib>=2.1.2']
PS.Util

2021-07-08 13:06 UTC, SerjKrukovZenoss approved these changes

2021-07-14 13:08 UTC, SerjKrukovZenoss approved these changes

2021-07-29 13:20 UTC, StevePC requested changes
do some clearing

2021-08-02 13:14 UTC, zensaiello requested changes

2021-08-02 13:14 UTC, zensaiello commented on ZenPacks/zenoss/CheckPointMonitor/README.rst
> +All Check Point devices must exist under the */Devices/Network/Check* Point device class.
Is it supposed to be `*/Devices/Network/Check Point*`  ?

2021-08-02 13:14 UTC, zensaiello commented on ZenPacks/zenoss/CheckPointMonitor/README.rst
> +    ==================  ==========================================================
Should be noted if this ZP supports SNMP v3 (It should by default) or not, if so, should mentioned the snmp v3 zProps.

2021-08-02 13:14 UTC, zensaiello commented on ZenPacks/zenoss/CheckPointMonitor/README.rst
> +=====================  ==============
Probably no longer need a "Daemon" section. Also, the PerfCollector will be zenpython, not zenperfsnmp.

2021-08-03 13:08 UTC, SerjKrukovZenoss approved these changes

2021-08-17 13:29 UTC, SerjKrukovZenoss requested changes

2021-08-17 13:29 UTC, SerjKrukovZenoss commented on ZenPacks/zenoss/CheckPointMonitor/modeler/plugins/CheckPoint/snmp/VsxDevice.py
> +                    'vsHAState': row.get('vsxStatusHAState')
you should monitor it

2021-08-23 13:17 UTC, StevePC requested changes

2021-08-23 13:17 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/jobs.py
> +        deviceClass = self.dmd.Devices.getOrganizer('/Network/Check Point/VSX/Device')
check to see if we can see into sub device-classes

2021-08-23 13:17 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/jobs.py
> +                message = "Device is not reported in the list of devices for this Gateway",
mention what action was taken

2021-08-23 15:17 UTC, mkotovska commented on ZenPacks/zenoss/CheckPointMonitor/jobs.py
> +        deviceClass = self.dmd.Devices.getOrganizer('/Network/Check Point/VSX/Device')
Checked. Yes, we can see sub device-classes

2021-09-01 13:17 UTC, StevePC requested changes

2021-09-01 13:17 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/modeler/plugins/CheckPoint/snmp/VsxRAID.py
> +        rm = RelationshipMap(compname=self.compname, relname=self.relname, modname=self.modname)
no self.compname

2021-09-01 13:17 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/modeler/plugins/CheckPoint/snmp/VsxRAID.py
> +            compname = volumeCompnames[volumeID]
check to ensure the volume exists

2021-09-01 13:17 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/modeler/plugins/CheckPoint/snmp/VsxRAID.py
> +                        'id': self.prepId('raidDisk_%s' % disk.get('raidDiskID')),
perhaps add volumeId to this to ensure unique

2021-09-01 13:17 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/zenpack.yaml
> +  - VsxRAIDVolume 1:M VsxRAIDDisk
should be MC

2021-09-02 13:29 UTC, StevePC requested changes

2021-09-02 13:29 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/modeler/plugins/CheckPoint/snmp/VsxRAID.py
> +            compname, parentID = volumeCompnames.get(volumeID, ('', ''))
need to check this result.  if there is no volume, we have no relation to attach to, so log an error and drop the disk

2021-09-02 13:29 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/modeler/plugins/CheckPoint/snmp/VsxRAID.py
> +                                 parentId=parentID,
parentID is not needed here

2021-09-07 13:47 UTC, StevePC requested changes

2021-09-07 13:47 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/zenpack.yaml
> +        datapoint: vsxStatusHAState_haState
should have a default value

2021-09-07 13:47 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/zenpack.yaml
> +            severity: Warning
maybe make this Critical just in case there is a critical state we don't know about

2021-09-20 13:40 UTC, StevePC requested changes

2021-09-20 13:40 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/jobs.py
> +            message = "Device moved because it's not in the list of devices returned for this Gateway",
this message is not currently used, it can be removed, or changed to the message used below and then used there.

2021-09-20 13:40 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/jobs.py
>                  # except Exception as ex:
It might be a good idea to refactor this a little so that the failure to add event is sent after the "will be created" event instead of before.

2021-09-20 13:40 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/jobs.py
> +                summary="VSX device {} reported from Gateway {}".format(devId, gatewayDev.id),
They summary should probably include the text of if we are adding the device or not, followed by the device and gateway IDs.  This ensure the user knows at a glance if a device was added, and i the ID are truncated due to length, they are still in the message.

2021-09-20 13:40 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/jobs.py
> +                message = "New Device reported from Gateway. New VSX device will be created"
the message here and below should contain the new device id and the gateway id, as the message will not be truncated at 128 characters.

2021-09-20 13:40 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/zenpack.yaml
> +        default: 'Unknown'
probably need an enum here for the non-default values

2021-09-22 13:11 UTC, StevePC requested changes
previous review comments

2021-09-23 13:14 UTC, StevePC requested changes

2021-09-27 11:50 UTC, mkotovska commented on ZenPacks/zenoss/CheckPointMonitor/dsplugins.py
> +    eventKey = 'VpnSiteToSiteStatus'
eventClassKey - fixed

eventKey used for deduplication (we don't want to use summary for this purpose because summary could be different)

2021-09-27 13:18 UTC, StevePC requested changes

2021-09-27 13:18 UTC, StevePC commented on ZenPacks/zenoss/CheckPointMonitor/zenpack.yaml
> +        eventClassKey: Cluster
make the keys more specific to this ZP/device so other mappings don't steal your events

2021-09-28 13:08 UTC, SerjKrukovZenoss approved these changes

2021-09-29 13:39 UTC, mkotovska commented on ZenPacks/zenoss/CheckPointMonitor/zenpack.yaml
> +                rpn: ${here/totalBlocks},/,100,*
if I'm not mistaken currently Configurable Datapoint works only for API and COMMAND not SNMP

2021-10-05 13:12 UTC, SerjKrukovZenoss requested changes
add "remove: true" into event mapping

2021-10-05 13:17 UTC, SerjKrukovZenoss approved these changes

2021-10-05 13:27 UTC, merged